# Generated by Django 4.0.2 on 2023-12-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0003_customuser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='parking_center',
        ),
        migrations.AddField(
            model_name='customuser',
            name='center',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='center',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
